#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details on this file.
#

name: $(SourceBranchName).$(Date:yyyyMMdd)$(Rev:.r)

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: UnitTest
  jobs:
  - job: UnitTest
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: 5.0.100-rc.2.20479.15
    - pwsh: dotnet restore
      displayName: Restore Dependencies
    - pwsh: dotnet build --configuration Release --no-restore
      displayName: Build Projects
    - pwsh: dotnet test --no-restore --verbosity normal
      displayName: Unit Test
