{
 "title": "Fabron",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Threads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(process_num_threads)" }
   ]
  },
  {
   "title": "Active Reminders",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(orleans_reminders_numberofactivereminders_current)"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Job Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(fabron_jobs_total) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Job Rates",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fabron_jobs_total[10s])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Job Schedule Tardiness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(fabron_jobs_schedule_tardiness_bucket[30s])) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(fabron_jobs_schedule_tardiness_bucket[30s])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(fabron_jobs_schedule_tardiness_bucket[30s])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{service=\"fabron\"} | json | LogLevel=\"Error\" | line_format \"Category: {{.Category}}\\nMessage: {{.Message}}\\nException: {{.Exception}}\""
    }
   ]
  }
 ]
}