name: CI
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.200
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Codecov
      uses: codecov/codecov-action@v1
  publish_image:
    name: Build & Push Container Image
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Push to GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./src/FabronService/Dockerfile
        push: true
        tags: |
          ghcr.io/dcarea/fabron-service:build.${{ github.run_number }}
          ghcr.io/dcarea/fabron-service:git.${{ github.sha }}
  deploy:
    name: Deploy
    needs: publish_image
    runs-on: ubuntu-latest
    environment: d001
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v1.0.1
    - name: Pulumi up
      run: |
        echo "${{secrets.KUBECONFIG}}" > .kubeconfig
        npm install
        pulumi stack select d001
        pulumi up --yes --skip-preview --suppress-permalink="true"
      working-directory: ./deploy
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        KUBECONFIG: .kubeconfig
        IMAGE_VERSION: build.${{ github.run_number }}
