name: Deploy Check
on:
  pull_request:
    branches: [ main ]
    paths: [ deploy/** ]
jobs:
  preview:
    name: Preview Changes
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v1.0.1
    - name: NPM install
      run: |
        npm install
        cd prometheus-operator-crds
        npm install
      working-directory: ./deploy
    - name: Pulumi up
      run: |
        echo "${{secrets.KUBECONFIG}}" > .kubeconfig
        pulumi stack select sandbox
        pulumi preview
      working-directory: ./deploy
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        KUBECONFIG: .kubeconfig
        IMAGE_VERSION: build.${{ github.run_number }}
