name: Deploy Preview
on:
  pull_request:
    branches: [ main ]
    paths: [ deploy/** ]
jobs:
  deploy_preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    environment: d001
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v1.0.1
    - name: Pulumi up
      run: |
        echo "${{secrets.KUBECONFIG}}" > .kubeconfig
        npm install
        pulumi stack select d001
        pulumi preview
      working-directory: ./deploy
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        KUBECONFIG: .kubeconfig
        IMAGE_VERSION: build.${{ github.run_number }}
