name: QZ
on:
  push:
    branches: [ qz ]
jobs:
  publish_image:
    name: Build & Push Container Image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - APP: qztester
          DOCKER_FILE: ./src/QzTester/Dockerfile
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Image Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.REGISTRY_ENDPOINT }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Push to Image Registry
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${{ matrix.DOCKER_FILE }}
        push: true
        tags: |
          ${{ secrets.REGISTRY_ENDPOINT }}/${{ matrix.APP }}:build.${{ github.run_number }}
  deploy:
    name: Deploy
    needs: publish_image
    runs-on: ubuntu-latest
    environment: sandbox
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v1.0.1
    - name: Pulumi up
      run: |
        echo "${{secrets.KUBECONFIG}}" > .kubeconfig
        yarn install
        pulumi stack select sandbox
        pulumi up --yes --skip-preview --suppress-permalink="true"
      working-directory: ./deploy
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        KUBECONFIG: .kubeconfig
        IMAGE_VERSION: build.${{ github.run_number }}
